language: python

python:
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install pandoc -y

# command to install dependencies
install:
  - pip install pipenv==2018.10.13
  - pipenv run make install

# command to run tests
script:
  - pipenv run make lint
  - pipenv run make test

# after_success:
#   - export CODECOV_TOKEN="211067ca-0d98-42d6-bd63-bf01171cc92f"
#   - bash <(curl -s https://codecov.io/bash)
